### PR TITLE
Updated the holopin.yaml to use the sdk badge

### PR DESCRIPTION
**Pull request by AjaySDwivedi1**
# Description

_Please explain the changes you've made_
Added code from issue #589 to holopin.yml
## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #589

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ ] Code compiles correctly
- [ ] Created/updated tests
- [ ] Extended the documentation

### CODE REVIEW

**Comment by shubham1172** [comment]
Hello @AjaySDwivedi1, welcome to this SDK 👋🏻 Can you please fix the DCO?

image

**Comment by AjaySDwivedi1** [comment]
> Hello @AjaySDwivedi1, welcome to this SDK 👋🏻 Can you please fix the DCO?
> 
> image

I added to the another commit. Let me know if that wrong and I'll do it again.

**Review by marcduiker — CHANGES_REQUESTED** [review]
Hi @AjaySDwivedi1 existing content of the holopin.yaml file should be removed. Only the YAML that is mentioned in the issue should be present in the file. Thank you!

**Comment by AjaySDwivedi1** [comment]
> Hi @AjaySDwivedi1 existing content of the holopin.yaml file should be removed. Only the YAML that is mentioned in the issue should be present in the file. Thank you!

Hey, I made the necessary changes. Let me know if I need to do anything else!

**Review by marcduiker — APPROVED** [review]
LGTM

**Comment by AjaySDwivedi1** [comment]
@marcduiker Did do the DCO right? The merge for the PR is still blocked. If I need to fix something let me know.

**Comment by marcduiker** [comment]
> @marcduiker Did do the DCO right? The merge for the PR is still blocked. If I need to fix something let me know.

@AjaySDwivedi1  The DCO/sign-off is missing from the initial commit. 

I think this should do it:

`git rebase --signoff HEAD~3`
`git push -f`

**Comment by AjaySDwivedi1** [comment]
@marcduiker Thank you! I was able to do the DOC right this time!

**Review by shubham1172 — APPROVED** [review]
Thanks @AjaySDwivedi1 for the PR and @marcduiker for your review, LGTM!

**Comment by marcduiker** [comment]
@holopin-bot @AjaySDwivedi1 Thank you for this contribution!

**Pull request merged**
